const stateKeys: string[] = [
  'endpoint',
  'apiPath',
  'loading',
  'isAuth',
  'token',
  'userDataPath',
  'isDevelopment',
  'json',
  'archives',
  'libraryData',
  'libraryFiles',
  'libraryFileId',
  'libraryTree',
  'todo',
  'events',
  'links',
  'todo',
  'filter',
  'fsmState',
  'timeout',
  'downloadsTargetPath',
  'notification',
  'error',
  'component',
  'selectedProjectKey',
  'history',
  'currentUser'
]

export default stateKeys
