DROP FUNCTION auth_user;
CREATE OR REPLACE FUNCTION AUTH_USER(
	LOGIN VARCHAR(80),
	PASS CHAR(64)
) RETURNS bool
AS $$
DECLARE 
	_PASS CHAR(64);
	_USER users;
	_RECORD TEMP_PASSWORD;
	
BEGIN 
	SELECT MD5($2) INTO _PASS;
	IF(
		EXISTS(
			SELECT * FROM USERS WHERE USERS.LOGIN = $1 AND USERS.PSWD_MD5 = _PASS
		)
	)
	THEN RETURN TRUE;
	ELSE 
		SELECT * FROM users INTO _USER WHERE USERS.LOGIN = $1;
		IF _USER IS NULL THEN 
			RETURN FALSE;
		ELSE
			SELECT * FROM TEMP_PASSWORD INTO _RECORD WHERE USER_ID = _USER.ID;
			IF _RECORD IS NULL THEN RETURN FALSE;
			ELSE 
				IF _RECORD.TEMP_PSWD_MD5 = _PASS THEN RETURN TRUE;
				ELSE RETURN FALSE;
				END IF;
			END IF;
		END IF;
	END IF;
END
	$$ LANGUAGE PLPGSQL;
