DROP FUNCTION auth_user;
CREATE OR REPLACE FUNCTION AUTH_USER(
	LOGIN VARCHAR(80),
	PASS CHAR(64)
) RETURNS bool
AS $$
DECLARE 
	_PASS CHAR(64);
	_FOUND users;
	_USER users;
	_RECORD TEMP_PASSWORD;
	
BEGIN 
	SELECT MD5($2) INTO _PASS;
	SELECT * FROM USERS INTO _FOUND WHERE USERS.LOGIN = $1;
	IF _FOUND IS NULL
		THEN RAISE EXCEPTION 'Erorr' USING HINT = 'Login is incorrect';
	END IF;
	
	SELECT * FROM USERS INTO _USER WHERE USERS.LOGIN = $1;
	
	SELECT * FROM USERS INTO _FOUND WHERE USERS.PSWD_MD5 = _PASS;
	IF _FOUND IS NULL THEN
		SELECT * FROM TEMP_PASSWORD INTO _RECORD WHERE USER_ID = _USER.ID;
		IF _RECORD IS NULL THEN 
			RAISE EXCEPTION 'Erorr' USING HINT = 'Password is incorrect';
		END IF;
		IF _RECORD.TEMP_PSWD_MD5 = _PASS THEN 
			DELETE FROM TEMP_PASSWORD WHERE USER_ID = _USER.ID;
			UPDATE USERS SET TEMP_PSWD_MD5 = _PASS WHERE USER_ID = _USER.ID;
			RETURN TRUE;
		ELSE
			RAISE EXCEPTION 'Erorr' USING HINT = 'Password is incorrect';
		END IF;
	ELSE RETURN TRUE;
	END IF;
END
	$$ LANGUAGE PLPGSQL;
