CREATE OR REPLACE FUNCTION AUTH_USER(
	LOGIN VARCHAR(80),
	PASS CHAR(64)
) RETURNS setof users
AS $$
DECLARE 
	_PASS CHAR(64);
	_USER users;

BEGIN 
	SELECT MD5($2) INTO _PASS;
	SELECT * FROM USERS into _USER WHERE USERS.LOGIN = $1 AND USERS.PSWD_MD5 = _PASS;
	RETURN NEXT _USER;
END
	$$ LANGUAGE PLPGSQL;
