CREATE TABLE USERS(
	ID int NOT NULL UNIQUE PRIMARY KEY,
	LOGIN VARCHAR(80),
	DISPLAYNAME VARCHAR(80),
	PSWD_MD5 CHAR(64),
	EMAIL VARCHAR(80),
	CREATE_DATE_TIME TIMESTAMPTZ,
	YANDEX_DISK_ACCESS_TOKEN text, 
	YANDEX_DISK_REFRESH_TOKEN text
);