DROP FUNCTION RESET_PASS;
CREATE OR REPLACE FUNCTION RESET_PASS(
	ID INT,
	OLDPASS CHAR(64),
	NEWPASS CHAR(64)
) RETURNS BOOL
AS $$

DECLARE
	_USER USERS;
	_PASS CHAR(64);

BEGIN
	SELECT MD5($2) INTO _PASS;
	SELECT * FROM USERS INTO _USER WHERE USERS.ID = $1;
	IF _USER IS NULL THEN 
		RAISE EXCEPTION 'Erorr' USING HINT = 'User not found';
	END IF;
	
	IF _PASS <> _USER.PSWD_MD5 AND _PASS <> _USER.TEMP_PSWD_MD5 THEN
		RAISE EXCEPTION 'Erorr' USING HINT = 'Password is incorrect';
	END IF;
	
	UPDATE USERS SET PSWD_MD5 = MD5($3) WHERE USERS.ID = $1;
	UPDATE USERS SET TEMP_PSWD_MD5 = null WHERE USERS.ID = $1;
	RETURN TRUE;
END
	$$ LANGUAGE PLPGSQL;
