CREATE OR REPLACE FUNCTION SET_TOKEN(
	_USER_ID int, 
	_TOKEN VARCHAR(80)
) RETURNS VOID
AS $$

DECLARE
	_DATE TIMESTAMPTZ;

BEGIN
	SELECT CURRENT_TIMESTAMP + '30 days' INTO _DATE;
	INSERT INTO TOKENS VALUES($1, $2, _DATE);
	
END 
 	$$ LANGUAGE PLPGSQL;