CREATE OR REPLACE FUNCTION SET_TOKEN(
	_USER_ID int, 
	_TOKEN VARCHAR(80)
) RETURNS VOID
AS $$

DECLARE
	_DATE TIMESTAMPTZ;

BEGIN
	SELECT CURRENT_TIMESTAMP + '30 days' INTO _DATE;
	IF(
		EXISTS(SELECT * FROM TOKENS WHERE USER_ID = $1)
	) 
	THEN
		UPDATE TOKENS SET TOKEN = $2 WHERE USER_ID = $1;
		UPDATE TOKENS SET TOKEN_EXPIRED = _DATE WHERE USER_ID = $1;
	ELSE
		INSERT INTO TOKENS VALUES($1, $2, _DATE);
	END IF;
	
END 
 	$$ LANGUAGE PLPGSQL;