export const AUTHOR = 'DN-WEB'
export const VK = 'vk.com/jimhucksly'
export const API_URL = 'https://dn-web.ru/api/v1/'
export const userDataFileName = 'App'
export const userPreferencesFileName = 'UserPreferences'
